// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvgfBmq6e1tLz5dePhTioMheZdG8Lqxfc',
    appId: '1:307162288146:web:88107673c28fe4312a48cb',
    messagingSenderId: '307162288146',
    projectId: 'acrossenglish-66b2a',
    authDomain: 'acrossenglish-66b2a.firebaseapp.com',
    storageBucket: 'acrossenglish-66b2a.firebasestorage.app',
    measurementId: 'G-S417QG2FPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqHSis5ACjaZnu-ucPRWxcW_v283tTS98',
    appId: '1:307162288146:android:9650b95c14463de02a48cb',
    messagingSenderId: '307162288146',
    projectId: 'acrossenglish-66b2a',
    storageBucket: 'acrossenglish-66b2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_1XjuOtGuV1P74--nvL7bBQGas0QsZ6g',
    appId: '1:307162288146:ios:e1118c10e1833a602a48cb',
    messagingSenderId: '307162288146',
    projectId: 'acrossenglish-66b2a',
    storageBucket: 'acrossenglish-66b2a.firebasestorage.app',
    iosBundleId: 'com.example.acrossenglish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_1XjuOtGuV1P74--nvL7bBQGas0QsZ6g',
    appId: '1:307162288146:ios:e1118c10e1833a602a48cb',
    messagingSenderId: '307162288146',
    projectId: 'acrossenglish-66b2a',
    storageBucket: 'acrossenglish-66b2a.firebasestorage.app',
    iosBundleId: 'com.example.acrossenglish',
  );
}
